language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
env:
 - CYTHON_INSTALL="pip install -q cython"
 - CYTHON_INSTALL=""
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-scipy
install:
 - $CYTHON_INSTALL

script:
 - python setup.py build_ext --inplace
 - nosetests
